- platform-configuration/pom.xml
- platform-configuration/src/main/java/org/codice/ddf/configuration/ConfigurationManager.java
- platform-configuration/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform-configuration/src/test/java/org/codice/ddf/configuration/ConfigurationManagerTest.java
Added the blueprint workaround for platform global.
> Ddf 1142 Add component-managed workaround for platform global, so the values get updated on startup

- security/interceptor/security-interceptor-anonymous/src/main/java/org/codice/ddf/security/interceptor/AnonymousInterceptor.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/39)
> DDF-1164 added check for null soap action to replace with empty string

- error/platform-error-impl/pom.xml
- security/handler/security-handler-anonymous/pom.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/40)
> DDF-1176 Upgrade frontend-maven-plugin to 0.0.23

- docs/pom.xml
- docs/src/assembly/bin.xml
- security/docs/pom.xml
- security/docs/src/assembly/bin.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/41)
> DDF-1158: improved documentation module to use .zip files.

- security-services-app/src/main/resources/features.xml
- security/pom.xml
- security/security-admin-module/.bowerrc
- security/security-admin-module/Gruntfile.js
- security/security-admin-module/bower.json
- security/security-admin-module/package.json
- security/security-admin-module/pom.xml
- security/security-admin-module/server-impl.js
- security/security-admin-module/server.js
- security/security-admin-module/src/main/grunt/tasks/bower.js
- security/security-admin-module/src/main/java/org/codice/ddf/security/admin/module/SecurityModulePlugin.java
- security/security-admin-module/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- security/security-admin-module/src/main/webapp/WEB-INF/web.xml
- security/security-admin-module/src/main/webapp/index.html
- security/security-admin-module/src/main/webapp/js/application.js
- security/security-admin-module/src/main/webapp/js/module.js
- security/security-admin-module/src/main/webapp/main.js
- security/security-admin-module/test.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/36)
> DDF-747 added security admin module

- security/interceptor/security-interceptor-anonymous-wrapper/pom.xml
- security/interceptor/security-interceptor-anonymous/pom.xml
- security/sts/security-sts-usernametokenvalidator/pom.xml
- security/sts/security-sts-usernametokenvalidator/src/main/java/org/codice/ddf/security/validator/username/UsernameTokenValidator.java
- security/sts/security-sts-usernametokenvalidator/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- security/sts/security-sts-usernametokenvalidator/src/test/java/org/codice/ddf/security/validator/username/TestUsernameTokenValidator.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/43)
> DDF-1182 fixed realm loading in UTValidator

- security/interceptor/security-interceptor-anonymous/pom.xml
- security/pep/security-pep-interceptor/pom.xml
- security/pep/security-pep-interceptor/src/test/java/ddf/security/pep/interceptor/TestPepInterceptorActions.java
- security/pep/security-pep-interceptor/src/test/java/ddf/security/pep/interceptor/TestPepInterceptorInvalidSubject.java
- security/pep/security-pep-interceptor/src/test/java/ddf/security/pep/interceptor/TestPepInterceptorNullAssertion.java
- security/pep/security-pep-interceptor/src/test/java/ddf/security/pep/interceptor/TestPepInterceptorNullAssertionToken.java
- security/pep/security-pep-interceptor/src/test/java/ddf/security/pep/interceptor/TestPepInterceptorNullMessage.java
- security/pep/security-pep-interceptor/src/test/java/ddf/security/pep/interceptor/TestPepInterceptorValidSubject.java
- security/pom.xml
- security/sts/security-sts-usernametokenvalidator/pom.xml
Fixed problem between JaCoCo and PowerMock and updated the coverage numbers back to what they were.
@shaundmorris, @stustison, please review.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/45)
> DDF-1174: Fixed problem between JaCoCo and PowerMock

- security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml
@stustison 
@pklinef
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/50)
> DDF-1404 Updated security-policy-context to include sources and security-coinfig

- security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml
Found this issues after the merge. 
@shaundmorris can you verify this and merge it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/52)
> DDF-1204 Fixes extra quote at end of required attributes default

- security/core/security-core-impl/pom.xml
- security/core/security-core-impl/src/main/java/ddf/security/assertion/impl/SecurityAssertionImpl.java
- security/filter/security-filter-login/src/main/java/org/codice/ddf/security/filter/login/LoginFilter.java
- security/platform-security-core-api/src/main/java/ddf/security/assertion/SecurityAssertion.java
@pklinef @shaundmorris
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/53)
> DDF-1222 changed the login filter so that it attaches a java.security.auth.Subject to the thread

- security/core/security-core-impl/src/main/java/ddf/security/service/impl/SecurityAssertionStore.java
@shaundmorris @mverret @clockard
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/54)
> DDF-1223 fixed the security assertion store so that it creates security tokens with a created and expires date

- security/sts/security-sts-anonymousvalidator/pom.xml
- solr/solr-factory/pom.xml
@shaundmorris 
@lessarderic
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/60)
> DDF-1233: lowered codecoverage minimums

- metrics/platform-metrics-collector/src/test/java/ddf/metrics/collector/rrd4j/RrdJmxCollectorTest.java
- metrics/platform-metrics-reporting/pom.xml
- metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/MetricsRetriever.java
- metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rest/MetricsEndpoint.java
- metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetriever.java
- metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rest/MetricsEndpointTest.java
- metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java
- metrics/platform-metrics-webconsole-plugin/src/main/java/ddf/metrics/plugin/webconsole/MetricsWebConsolePlugin.java
- metrics/platform-metrics-webconsole-plugin/src/test/java/ddf/metrics/plugin/webconsole/MetricsWebConsolePluginTest.java
- Normalize time math to UTC
- Fix auto-sizing of regular XLS sheet columns
- Tidy up some javadocs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/56)
> DDF-1243 Add an incremental summary report.

- .gitignore
- security-services-app/src/main/resources/features.xml
- security/filter/security-filter-authorization/src/main/java/org/codice/ddf/security/filter/authorization/AuthorizationFilter.java
- security/pdp/pom.xml
- security/pdp/sample-xacml/pom.xml
- security/pdp/sample-xacml/src/main/java/ddf/security/pdp/xacml/SampleXACML.java
- security/pdp/sample-xacml/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- security/pdp/sample-xacml/src/main/resources/access-policy.xml
- security/pdp/security-pdp-xacmlrealm/src/main/java/ddf/security/pdp/xacml/realm/XACMLRealm.java
Changed AuthorizationFilter to always pass an ActionPermission to the PDP and fixed a String cast issue in XACMLRealm.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/61)
> DDF-1257 - Resolved merge conflicts with reformatting changes

- platform-http-proxy/pom.xml
- platform-http-proxy/src/main/java/org/codice/ddf/platform/http/proxy/HttpProxy.java
- platform-http-proxy/src/test/java/org/codice/ddf/platform/http/proxy/TestHttpProxy.java
- platform-http-proxy/src/test/resources/test.wsdl
- pom.xml
@pklinef @shaundmorris @brendan-hofmann 
@AzGoalie is the hero
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/63)
> DDF-1252 updated proxy lib to accept a camel bean for outgoing response and added policy rewrite bean to platform proxy

- security/common/pom.xml
- security/common/src/main/java/org/codice/ddf/security/common/jaxrs/RestSecurity.java
- security/common/src/test/java/org/codice/ddf/security/common/jaxrs/RestSecurityTest.java
@mverret @djblue @shaundmorris 
@djblue can hero
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/66)
> DDF-1294 added check for https scheme to add cookie method

- security/sts/security-sts-anonymousvalidator/pom.xml
@figliold, can you do a quick review and merge. This is needed to fix the Java 8 build in Bamboo.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/70)
> Updated code coverage percent for Java 8 to make the build pass.

- error/platform-error-impl/Gruntfile.js
- error/platform-error-impl/package.json
- error/platform-error-impl/pom.xml
- error/platform-error-impl/src/main/grunt/tasks/bower.js
- security/handler/security-handler-anonymous/Gruntfile.js
- security/handler/security-handler-anonymous/package.json
- security/handler/security-handler-anonymous/pom.xml
- security/handler/security-handler-anonymous/src/main/grunt/tasks/bower.js
@andrewkfiedler @pklinef
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/72)
> DDF-1308 fixed bower build to no longer overwrite the bower.json file for every build

- solr/platform-solr-server-standalone/src/main/resources/solr/conf/schema.xml
@kcwire
@millerw8
@pklinef
@wmcnalli
@jlcsmith
@beyelerb
@emanns95
@jrnorth
@coyotesqrl
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/67)
> DDF-1264 updated text_ws in schema.xml type descriptor to use for wildcard searching

- solr/platform-solr-server-standalone/src/main/resources/solr/conf/schema.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/76)
> DDF-1264 added new index for case sensitive wildcard searches

- metrics/platform-metrics-ui/Gruntfile.js
- metrics/platform-metrics-ui/package.json
- metrics/platform-metrics-ui/pom.xml
- metrics/platform-metrics-ui/src/main/grunt/tasks/bower.js
@pklinef @andrewkfiedler
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/75)
> DDF-1308 fixed issues with bower.json in metrics admin module

- admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/ConfigurationAdmin.java
This is the same pull request as https://github.com/codice/ddf-admin/pull/92 but moving here because of repository merges.
@brendan-hofmann
@brianfelix
@kguerriero
@shaundmorris
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/81)
> DDF-1318: Fixed CSW Source creation

- pom.xml
- Removed distribution management that was overriding the correct configuration from ddf-parent pom.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/83)
> DDF-1341 Removing unnecessary / wrong distribution management in pom

- .gitignore
Yet another monster.
@pklinef 
@tbatieConnexta 
@jckilmer
@rzwiefel
@roelens8
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/82)
> DDF-1342  Missing .gitignore value from the ddf-solr and ddf-admin merges

- metrics/platform-metrics-webconsole-plugin/pom.xml
- notifications/core/platform-core-notificationcommands/pom.xml
- platform-commands/pom.xml
- pom.xml
- security/encryption/platform-security-encryption-commands/pom.xml
Updated the karaf version to 2.4.3. Updated dependencies as needed. 
@mrmateo @shaundmorris @pklinef please verify these changes. 
@shaundmorris, once approved can you be the committer for this PR?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/84)
> DDF-1224 Updated karaf to version 2.4.3

- parser/test-domain/pom.xml
- parser/xml/pom.xml
Bad pom parentage. Bad, bad, bad.
@kcwire 
@shaundmorris
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/91)
> DDF-1312 Fixes parent pom issue.

- security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/SimpleAuthzRealm.java
- security/pdp/security-pdp-authzrealm/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- security/pdp/security-pdp-authzrealm/src/test/java/ddf/security/pdp/realm/test/SimpleAuthzRealmTest.java
- security/platform-security-core-api/src/main/java/ddf/security/policy/extension/PolicyExtension.java
@pklinef @mverret @AzGoalie
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/87)
> DDF-1360 added policy extension interface and updated Java PDP to look for those services

- platform-http-proxy/src/main/java/org/codice/ddf/platform/http/proxy/HttpProxy.java
- platform-http-proxy/src/test/java/org/codice/ddf/platform/http/proxy/TestHttpProxy.java
- platform-http-proxy/src/test/resources/test.wsdl
@shaundmorris
@stustison
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/93)
> DDF-1368 Fixed HttpProxy gzip handling

- admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/ConfigurationAdminExt.java
- security/security-admin-module/pom.xml
@mverret will hero
@pklinef 
@brendan-hofmann 
@andrewkfiedler
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf-platform/86)
> DDF-1343: Exposed methods needed for MBean
